### ISSUE TITLE
when to use implicitly unwrap?

### ISSUE THREAD

**Issue by cnfshandson** [uchicago-mobi/2016-Winter-Forum#11]
This is from "connect the UI to Code", why don't we use implicitly unwrap (UITextField) in the argument?

@IBOutlet weak var nameTextField: UITextField!

 func textFieldShouldReturn(textField: UITextField) -> Bool

 func textFieldDidEndEditing(textField: UITextField) 

Thank you.

**Comment by susanstevens** [comment]
@cnfshandson This is a great question.  Optionals are at the heart of Swift, and understanding why they exist and how they work is crucial.

In the two methods you listed, textField is a non-optional variable, meaning it can never be nil.  These methods are called automatically when the user interacts with the text field you created.  (In fact, you should never call these methods directly in your code.)  Since they're only called when the user interacts with a text field, you can safely assume that the text field exists and can be passed to the method as a non-optional parameter.

The flip side of your question is why IBOutlets ARE implicitly unwrapped optionals (and they always are).  When you use an implicitly unwrapped optional, you're basically promising the compiler that although the variable is nil when you create it, it won't be nil when you use it.  (If it is nil when you use it, you'll find out quickly because your app will crash.)  It's safe to make this promise with an IBOutlet, because while it will be nil at the time the view controller is created, we can rest assured that Interface Builder will have created it by the time we want to use it.

Here's an article I found that explains all of this nicely: https://s3.amazonaws.com/udacity-hosted-downloads/ud585/docs/Optionals.pdf.
