### ISSUE TITLE
Long logs when I display UIAlertController when GitHub is unavailable

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#124]
I successfully notify users when GitHub is unavailable, but the console shows a long message (and it prints the stack, which I didn't include in this screenshot)
![screen shot 2016-02-07 at 2 21 29 pm](https://cloud.githubusercontent.com/assets/11274851/12874999/1ba71608-cda6-11e5-9d99-13ae02965af5.png)

Everything works and I don't get warnings except for this message in the log. Is this okay, or should I change my implementation? My current implementation involves saving a `statusCode` variable. In the networking code (in my GithubNetworkingManager), if the `NSHTTPURLResponse` isn't nil, I save the status code. Then in the `issuesRequestion` call in `DataTableViewController`, I check the status code and display the alert controller if the status code isn't 200. I'm not sure how else to do it...

**Comment by susanstevens** [comment]
Your approach is right.  It looks like the error that's printing isn't an error with your application, it's the result of this section of code from the `issuesRequestion` method:

```
      guard error == nil else {
        print("error: \(error!.localizedDescription): \(error!.userInfo)")
        completion(nil)
        return
      }
```

When NSURLSession can't load data from the network because there isn't an Internet connection, it returns an error, which you're printing to the console.  So your app is working as expected.

However, the last line in your screenshot that says "This application is modifying the auto layout engine from a background thread..." suggests that you're doing some UI updates in the `issuesRequestion` completion block without calling `dispatch_async`.  You definitely want to fix this.

**Comment by aaizuss** [comment]
@susanstevens Ok, I just tried wrapping my conditional where I check the status code and show the alert  with `dispatch_async(dispatch_get_main_queue())`, but now the alert controller doesn't appear at all.   

EDIT: Never mind - fixed it. Should the activity indicator view also disappear when the connection fails? Mine remains visible (It appears and disappears properly when I have WiFi on, though)

**Comment by susanstevens** [comment]
Awesome!  I'd recommend removing it whenever your networking call finishes - whether successful or not.
