### ISSUE TITLE
Review of Past Assignment 

### ISSUE THREAD

**Issue by cnfshandson** [uchicago-mobi/2016-Winter-Forum#143]
Hi I found the previous project (assign 4 & 5) challenging and fun. As a absolute beginner, I start to get some sense now. I think it would be great if we could schedule a TA section to go over the previous project. I would like to see how the professionals tackle all these problems and compare to my own solution.I think it would be a great opportunity to learn more and further understand iOS programming.

Is it possible? Thank you.

**Comment by susanstevens** [comment]
@cnfshandson Is there a particular section of the assignment you would like to go over?  I'd be happy to post a gist showing how I would have approached a particular part of the assignment.  I can also answer any questions you have about HW 4 and 5 at my office hours on Sunday.  I'm sure Bob and Dana are happy to answer questions at their office hours as well.

Most of HW 4 was very similar to the Food Tracker tutorial from HW 1 and 3.  It's definitely worth taking a look at that tutorial again if you need a refresher on displaying data in a table view controller or passing data to a detail view controller.  (There were several tutorials like this one that I went through multiple times when I was starting to learn iOS development.)

**Comment by bobby-digital-23** [comment]
@cnfshandson 
It's great to see you showing an interest in learning more about iOS development! Please come to office hours and anyone of us can give you suggestions. As Susan righteously suggested, rereading the tutorial is a great way to reinforce what you've learned. What might have seemed difficult a month ago might seem easy now but it might also lead to more questions which is a good thing! Definitely follow that train of thought and if you ever have any specific questions and/or would like to do a code review in person, please email me and I'd be happy to setup a time to meet with you.

Andrew does an amazing job of teaching the fundamentals of iOS development in a very limited amount of time. If you've enjoyed this class, I highly recommend taking the advance class next quarter. You will learn many more important (and IMO, super fun) concepts which simply can't be covered in one quarter. Most schools take two semesters, or more, to cover what Andrew effectively teaches in two quarters - not an easy feat! :-)

Btw, I highly recommend reading this short essay by [Peter Norvig](https://en.wikipedia.org/wiki/Peter_Norvig).
[Teach Yourself Programing in Ten Years](http://norvig.com/21-days.html)

**Comment by nicholasfasolt** [comment]
Just to echo the TA's - using the Foodtracker tutorial as a guide through assignment 4 was immensely helpful. The project is very similar, but implementing the functionality myself instead of copying the code forced me to really think about and understand what the code is doing. I actually went back reread the full tutorial after week three and have been referencing it constantly throughout the last two weeks.

**Comment by tabinks** [comment]
I concur with everything (especially about the part about Andrew).

It would be best for students to bring their assignments to an office hours to go over individually.  There are (as the TAs will attest) many different approaches and coding styles to implementing the functionality in the assignments.  This often is heavily influenced by what languages you knew before. 

I don't like to publish an "answer" to the assignments because different students solve problems in different ways (and they can all be correct).  This can often be more confusing to students who are at the beginning stages of iOS development.  Students will relate to Swift and UIKit differently and develop their own practices.  Eventually, they will start to seek out "best" practices once they have a better understanding of the material.

**Comment by cnfshandson** [comment]
Hi everyone!
Thank you for your great comments. I will definitely bring my assignments to the TA section. I agree that assign 4 is like a test of how well you understand the assign 3 tutorial and assign 5 brings to a higher level. One difficulty of assign 5 for me is I had some ideas to implement the requirement, but then figured out Swift doesn't work that way (or maybe it does, I just don't know how). Another difficulty is that even I made it work, well because some smart guy in stack overflow said it would work, but I had hard time to fully understand why. 
Thank you very much

**Comment by bobby-digital-23** [comment]
@cnfshandson 
You're most welcome! What specific requirement in Assignment 5 are you referring to and which Stack Overflow post did you read?

**Comment by cnfshandson** [comment]
Thank you. More than one, let me summarize them and show you during the discussion. We can open another issue after the discussion and share the results with the class.
