### ISSUE TITLE
Changing label text in UIView 

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/2016-Winter-Forum#160]
I created a UIView that moves onto the screen to alert the user of a win or a draw. I have tried using UILabel and UITextField to store the text before animating the UIView onto the screen, but changing the UILabel or UITextField text makes the UIView invisible (though it still animates). Anyone know what the problem might be?

**Comment by lw334** [comment]
I used UITextView instead of UITextField and it works fine. Don't know if this is the root cause of your problem thou.

**Comment by susanstevens** [comment]
@manglano Just so I'm clear, is the UIView animating correctly when you don't change the text?

I noticed yesterday that you were printing "done" in the completion block of `animateWithDuration` and that "done" was getting printed out multiple times.  Makes me wonder if the animation is getting called multiple times... One animation options you can set is `.BeginFromCurrentState`.  If the animation block is called while the view is currently animating, it'll pick up from wherever the view is at the time, instead of cutting off the previous animation and starting over.

**Comment by susanstevens** [comment]
If the animation block _is_ getting called multiple times in a row, you could also investigate why this is happening and write some logic to make sure it only gets called once at the end of the game.

**Comment by ghost** [comment]
I changed the view to contain a UITextView instead & now it works. Thank you.
