### ISSUE TITLE
Good read about the modern app economy

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#201]
http://www.theverge.com/2016/3/2/11140928/app-store-economy-apple-android-pixite-bankruptcy

**Comment by tabinks** [comment]
This is a great read.  This echoes a lot of what I've seen over the past years.  @aaizuss Thank you for sharing.

A positive takeaway from this is to see how a small project grew into a successful business in the app economy.  

The one thing that these developer stories never seem to acknowledge is that maybe an app didn't find success because it didn't actually meet a demand (or wasn't that good).  I've never used any of those, so I'm speaking in general terms.  There was a "famous" story in 2009 about two competing skee-ball apps that were released very close together...one a success and one not so much.  For historical context, read http://gedblog.com/2009/09/28/losing-ireligion/ and/or https://marco.org/2009/10/09/the-two-app-stores. The developer of one claimed the App Store didn't allows them to be successful...despite most users saying the app just wasn't that good compared to its competitor.

I would also add that another positive thing (that I hope that many of you are starting to realize), is that that the cumulative skills you are learning in the MPCS program would allow you to compete with any product on the App Store.  You're not going to compete with Facebook for users, but could you make an app to show a feed of text and images...of course.  Yours would even make use of split view controller to provide a better user experience.  There's the app and then their's the business behind the app.  These are very different and very difficult to reconcile.

This was suppose to be inspiring....now get to work on your final projects...put them in the App Store...and come back and update this issue with your success story.

**Comment by tabinks** [comment]
Any @uchicago-mobi/alumni have anything to add?
