### ISSUE TITLE
Executive Summary and Marketing Materials

### ISSUE THREAD

**Issue by cjhodnefield** [uchicago-mobi/2016-Winter-Forum#222]
Should our executive summary address and describe the expected final functionality of our app, or the functionality we have done for project submission? This may not apply to everyone, but my game in particular will be missing a lot of extra features for this project submission (I plan to add those features later before submitting to the app store), but I could go ahead and describe them in the summary if needed.

As for the marketing materials, are there any best practices when it comes to choosing keywords? I've gotten a bit of a sense of it from googling the app store requirements, but more info would be great.

**Comment by susanstevens** [comment]
You're only expected to describe the functionality you've actually implemented.  You're welcome to include the additional features you're planning to implement, just make sure you clarify which features you've implemented and which you're planning to implement later so that we're not looking for something that isn't there.

As far as keywords go, just pick words that describe your app or that you think people who would be interested in your app are likely to search.

**Comment by cjhodnefield** [comment]
Sounds good, thank you!

**Comment by tabinks** [comment]
Agreed.

As for keywords, you'd be surprised how many apps that are not Facebook turn up when you type Facebook.  Some unscrupulous developers may sneak some unrelated but highly popular words into their list.
