### ISSUE TITLE
View doesn't show data till second click

### ISSUE THREAD

**Issue by gopalp19** [uchicago-mobi/2016-Winter-Forum#71]
In my viewDidLoad methods, I do my request to GitHub, and I get the data back and parse through it. But the first time of clicking the tab in the tab button bar to go to the view, I can see the data returning from the calls, but it doesnt update my scene with the cells/circle shapes...only when I switch to a different tab and come back, the view has the table cells/shapes then.

For instance, when I switch to the Status tab, I get the issues JSON and parse everything in viewDidLoad, but I won't see my shapes till I switch to the Open Items tab and then return to Status. Anyone have any clue what I could be missing?

**Comment by danakatz** [comment]
@gopalp19 Remember that you're fetching GitHub data asynchronously. Luckily, the code that the professor has provided for your API calls comes with a completion block, which you can use to tell the view controller what to do when the API call finishes. You might also find the discussion in https://github.com/uchicago-mobi/2016-Winter-Forum/issues/67 helpful.

As a general note, think carefully about what exactly should happen in each phase of the [view controller lifecycle](https://developer.apple.com/library/ios/referencelibrary/GettingStarted/DevelopiOSAppsSwift/Lesson4.html#//apple_ref/doc/uid/TP40015214-CH6-SW1). You may need to use methods other than `viewDidLoad()` to make sure you get the expected behavior when switching between tabs.

**Comment by ghost** [comment]
I'm having a similar concern--The data doesn't load until the user taps the screen or refreshes?

**Comment by gopalp19** [comment]
@danakatz I went over the controller lifecycle link you added and tried to use viewWillAppear() as well, but I'm still facing the same issue. 

@manglano Yea, I'm having that same issue with the All/Open issues tabs. The data is there, but I need to click the table on screen and it immediately shows up.

**Comment by danakatz** [comment]
@manglano @gopalp19 It sounds like the problem is that the table loads before the data comes back from the API -- as I mentioned, the API call happens asynchronously, while UI updates happen on the main thread. How can you update the table _after_ the API call is finished? Are you doing something in particular on refresh or tab switch that you might need to also do on initial data load? Please look specifically at @susanstevens's comment in https://github.com/uchicago-mobi/2016-Winter-Forum/issues/67.

**Comment by tabinks** [comment]
Repost from #67:  Ask yourself 2 questions:
If there is data in `issues`, how many rows should there be?
If there is no data in `issues`, how many rows should there be?

**Comment by tabinks** [comment]
If you are logging out the data to the console, then you know, at that point, the data is available in `issues`.  That might be a good time to tell the table to update itself.

**Comment by susanstevens** [comment]
For anyone still struggling with this, take a look at the NSURLSession tutorial linked to on the assignment webpage.  Once you have data in `issues` you need to tell your table view to reload it's data AND you need to do so on the correct thread.  Network calls happen asynchronously (i.e., on a background thread), but UI updates should always happen on the main thread.

**Comment by gopalp19** [comment]
I think I got it, thank you!
